apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.app.name }}-migrations-job"
  labels:
    app: migrations
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migrations
        image: "{{ .Values.image.registry }}/{{ .Values.app.name }}-migrations:{{ .Chart.AppVersion }}"
        command: ["migrate"]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
{{ toYaml .Values.env | indent 8 }}