apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-5"
  name: {{ .Values.app.name }}
spec:
  refreshInterval: 6h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: {{ .Values.app.name }}
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: DATABASE_URL
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: ENCRYPTION_KEY

