http:
  hostname: ""
  port: 8000
  readTimeout: "5s"
  writeTimeout: "10s"
  idleTimeout: "2m"
  shutdownTimeout: "10s"
  tls:
    enabled: false
    certificate: ""
    key: ""

app:
  name: "Pagoda"
  # We manually set this rather than using the HTTP settings in order to build absolute URLs for users
  # since it's likely your app's HTTP settings are not identical to what is exposed by your server.
  host: "http://localhost:8000"
  environment: "local"
  # Change this on any live environments.
  encryptionKey: "?E(G+KbPeShVmYq3t6w9z$C&F)J@McQf"
  timeout: "20s"
  passwordToken:
      expiration: "60m"
      length: 64
  emailVerificationTokenExpiration: "12h"

cache:
  capacity: 100000
  expiration:
    staticFile: "4380h"

database:
  driver: "pgx"
  connection: "postgresql://startmeup:secret@localhost:5432/startmeup?sslmode=disable"
  test_connection: "postgresql://startmeup:secret@localhost:5432/startmeup_test?sslmode=disable"

files:
  directory: "uploads"

tasks:
  goroutines: 2
  releaseAfter: "15m"
  cleanupInterval: "1h"
  shutdownTimeout: "10s"
  pollInterval: "5s"

mail:
  hostname: "localhost"
  port: 25
  user: "admin"
  password: "admin"
  fromAddress: "admin@localhost"
