apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: production
  name: production
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: preview
  name: preview
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: core
  name: core
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: postgres
  name: postgres

