---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-secrets-store
  interval: 3m
  retryInterval: 2m0s
  wait: true
  path: "./clusters/resources/startmeup/postgres"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
