---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: shared-components
  namespace: flux-system
spec:
  interval: 3m
  retryInterval: 2m0s
  wait: true
  path: "./clusters/shared"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
