apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: startmeup
  namespace: production
spec:
  interval: 1m
  chart:
    spec:
      chart: startmeup
      version: ">=0.0.1"
      sourceRef:
        kind: HelmRepository
        name: startmeup
        namespace: flux-system
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
